[package]
name = "docker-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = "0.4.44"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
anyhow = "1.0.68"
urlencoding = "2.1.2"